/*
WCC2 Final Project: Sound_Face
[An interactive and performative facial instrument]

By Andrés Serna

Last update: 15 April 2026

Blurb: 
This project is an interactive computer vision system built with p5.js, MediaPipe, and the p5.sound library. 
It translates facial gestures into a performative audiovisual instrument. Using MediaPipe, the system detects a face
via webcam and extracts the coordinates and relative distances of facial landmarks. These measurements are mapped to 
sound parameters through p5.sound. Visually, the instrument is represented as a particle system that responds dynamically
to the audio generated by specific facial gestures.

Acknowledgments:

- I took the base for this code from the teacher Rebecca Aston in one of the code examples in VLE in:
  https://editor.p5js.org/beckyaston/sketches/431uCva8m
  
- The further MediaPipe implementation was made by me and hours of research of it documentation and code examples in:
  https://mediapipe-studio.webapps.google.com/home

- Generative AI Tools was also use to help part of the development and debugging of this project, specially when it comes to the
  implementation of the sound-engine. The specific prompts and lines that have been generated will be acknowledged in the PDF document for this project. 
*/


///// GLOBAL VARIABLES

// MediaPipe classes to build the face tracker during preload.
let FaceLandmarker;
let FilesetResolver;

// These variables store the live tracking result and the webcam feed.
let myFaceLandmarker;
let faceLandmarks;
let myCapture;
let lastVideoTime = -1;

// Only the face tracker is active, and blendshapes are enabled because the emotion layer depends on them.
const trackingConfig = {
  doAcquireFaceMetrics: true,
  cpuOrGpuString: "GPU",
  maxNumFaces: 1,
};

// Landmarks I used for sound and interface control.
const FACE_POINTS = {
  leftEyeOuter: 33,
  leftEyeUpper: 159,
  leftEyeLower: 145,
  rightEyeOuter: 263,
  rightEyeUpper: 386,
  rightEyeLower: 374,
  mouthLeft: 61,
  mouthRight: 291,
  mouthUpper: 13,
  mouthLower: 14,
  browLeft: 105,
  browRight: 334,
  noseTip: 1,
};

// These groups help me loop through features and emotion values without repeating code.
const FEATURE_KEYS = ["mouthOpen", "mouthWidth", "browRaise", "eyeOpen"];
const EMOTION_KEYS = ["angry", "happy", "disgust", "surprised", "fear", "sadness"];
const HUD_EMOTIONS = [
  { key: "angry", label: "angry" },
  { key: "happy", label: "happy" },
  { key: "sadness", label: "sad" },
  { key: "surprised", label: "surprised" },
  { key: "disgust", label: "disgust" },
  { key: "fear", label: "fear" },
];

// This is the title shown in the middle of the top HUD.
const PROJECT_TITLE = "SOUND FACE";
// This is the main web font I want for the interface.
const HUD_FONT = "Space Mono";
// This fallback keeps the HUD readable while the web font is still loading.
const HUD_FONT_FALLBACK = "monospace";


////// EMOTIONS THRESHOLDS AND SOUND STYLE MAPS

// Each emotion uses its own threshold because some states are easier to trigger than others.
const EMOTION_THRESHOLDS = {
  angry: 0.16,
  happy: 0.2,
  disgust: 0.15,
  surprised: 0.17,
  fear: 0.16,
  sadness: 0.15,
};

// These values control how dense the cloud is and how the webcam preview sits in the frame.
const STAGE_CONFIG = {
  particleCount: 620,
  particleCountMin: 180,
  previewWidth: 220,
  previewAspect: 0.75,
  previewMargin: 24,
};

// Keeping the HUD values together makes it easier to adjust the layout during testing.
const HUD_CONFIG = {
  margin: 24,
  topHeight: 42,
  bottomHeight: 120,
  panelGap: 14,
  barHeight: 8,
};

// Each emotion has one shared colour/sound profile so the system feels consistent across visuals and audio.
const EMOTION_STYLES = {
  idle: {
    hueMin: 0,
    hueMax: 0,
    sat: 0,
    bri: 100,
    alphaMax: 0.38,
    pulseWave: "triangle",
    pulseFreq: 220,
    release: 0.22,
    triggerCooldown: 850,
  },
  angry: {
    hueMin: 0,
    hueMax: 16,
    sat: 88,
    bri: 100,
    alphaMax: 0.55,
    pulseWave: "sawtooth",
    pulseFreq: 130,
    release: 0.16,
    triggerCooldown: 600,
  },
  happy: {
    hueMin: 42,
    hueMax: 58,
    sat: 82,
    bri: 100,
    alphaMax: 0.58,
    pulseWave: "triangle",
    pulseFreq: 392,
    release: 0.22,
    triggerCooldown: 700,
  },
  disgust: {
    hueMin: 100,
    hueMax: 135,
    sat: 80,
    bri: 92,
    alphaMax: 0.42,
    pulseWave: "square",
    pulseFreq: 175,
    release: 0.28,
    triggerCooldown: 950,
  },
  surprised: {
    hueMin: 24,
    hueMax: 34,
    sat: 86,
    bri: 100,
    alphaMax: 0.58,
    pulseWave: "triangle",
    pulseFreq: 520,
    release: 0.14,
    triggerCooldown: 500,
  },
  fear: {
    hueMin: 275,
    hueMax: 300,
    sat: 72,
    bri: 96,
    alphaMax: 0.48,
    pulseWave: "square",
    pulseFreq: 310,
    release: 0.2,
    triggerCooldown: 650,
  },
  sadness: {
    hueMin: 205,
    hueMax: 228,
    sat: 74,
    bri: 96,
    alphaMax: 0.4,
    pulseWave: "sine",
    pulseFreq: 196,
    release: 0.35,
    triggerCooldown: 1100,
  },
};

// These pitch sets are simple enough to control the instrument but still give each emotion its own mood.
const EMOTION_SCALES = {
  idle: [0, 2, 4, 7, 9],
  angry: [0, 1, 3, 5, 7, 8, 10],
  happy: [0, 2, 4, 7, 9],
  disgust: [0, 1, 3, 6, 7, 10],
  surprised: [0, 2, 4, 6, 7, 9, 11],
  fear: [0, 1, 3, 5, 6, 8, 10],
  sadness: [0, 2, 3, 5, 7, 8, 10],
};

// A different root note shifts the tonal centre for each emotion.
const EMOTION_ROOTS = {
  idle: 48,
  angry: 40,
  happy: 55,
  disgust: 43,
  surprised: 60,
  fear: 50,
  sadness: 45,
};


/////// LIVE STATE

// I keep both raw and smoothed values because the face data is useful but naturally noisy.
const featureState = {
  raw: {
    mouthOpen: 0,
    mouthWidth: 0,
    browRaise: 0,
    eyeOpen: 0,
    headTilt: 0,
  },
  smooth: {
    mouthOpen: 0,
    mouthWidth: 0,
    browRaise: 0,
    eyeOpen: 0,
    headTilt: 0,
  },
};

// The baseline stores each user's neutral face so the emotion logic reacts to change, not fixed facial anatomy.
const baselineState = {
  blendshapes: {}, // Moving neutral value for each MediaPipe blendshape name.
  features: {
    mouthOpen: 0, // Neutral geometric mouth opening.
    mouthWidth: 0, // Neutral geometric mouth width.
    browRaise: 0, // Neutral geometric brow height.
    eyeOpen: 0, // Neutral geometric eye openness.
  },
  frameCount: 0, // Counts how many frames have contributed to the baseline.
  ready: false, // Turns true once the baseline has enough data to trust.
};

// Emotion scores remain continuous internally, then a small state machine turns them into a stable label.
const emotionState = {
  scores: createEmotionScoreMap(), // Continuous strength value for every emotion.
  current: "idle", // Emotion currently used by sound, particles, and HUD.
  candidate: "idle", // Possible next emotion before it becomes stable enough to commit.
  holdFrames: 0, // Number of frames the candidate has stayed dominant.
  confidence: 0, // Strength of the current emotion after smoothing.
  lastTriggerTime: -Infinity, // Starts at negative infinity so the first valid emotion can trigger immediately.
};

const appState = {
  audioReady: false, // True once the p5.sound graph exists.
  soundPaused: false, // True when the Web Audio context is suspended.
  hasFace: false, // True when MediaPipe currently sees a face.
  hudFontReady: false, // True after the browser confirms the HUD font is loaded.
  faceProximity: 0.35, // Live estimate of how close the face is to the webcam.
};

// The HUD bars have their own easing so the readout feels animated rather than jumpy.
const hudState = {
  bars: createEmotionScoreMap(), // Separate eased values for the bottom emotion meters.
};

// These numbers are only for the HUD readout, not for the sound logic itself.
const engineState = {
  mainFreq: 0, // Main oscillator frequency shown in the HUD.
  cutoff: 0, // Main filter cutoff shown in the HUD.
  level: 0, // Approximate main layer amplitude shown in the HUD.
};

let synthVoice; // Main pitched layer.
let subVoice; // Low support layer.
let padVoice; // Softer harmonic layer.
let airNoise; // Noise layer that adds breath and texture.
let filterNode; // Filter shared by the main voice and bass.
let padFilter; // Filter just for the pad.
let noiseFilter; // Filter just for the noise layer.
let masterGain; // Final output bus.
let amplitudeAnalyzer; // Reads the final mix level for the visuals.
let emotionPulse; // Short tone used for emotion accents.
let emotionPulseFilter; // Filter for the accent tone.
let accentNoise; // Noise burst paired with the accent tone.
let accentNoiseFilter; // Filter for the accent noise.
let delayNode; // Delay effect on the master bus.
let reverbNode; // Reverb effect on the master bus.
let particles = []; // Shared particle array used by the particle system file.


///////// PRELOAD AND SETUP

// I load MediaPipe before setup so the face detector exists as soon as the webcam starts.
async function preload() {
  try {
    // This imports the MediaPipe vision bundle from the CDN.
    const mediapipeModule = await import(
      "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.js"
    );

    // I only store the two classes this project actually needs.
    FaceLandmarker = mediapipeModule.FaceLandmarker;
    FilesetResolver = mediapipeModule.FilesetResolver;

    // This prepares the WASM files MediaPipe uses internally.
    const vision = await FilesetResolver.forVisionTasks(
      "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm"
    );

    // The detector is set for one live face and blendshape output.
    myFaceLandmarker = await FaceLandmarker.createFromOptions(vision, {
      numFaces: trackingConfig.maxNumFaces,
      runningMode: "VIDEO",
      outputFaceBlendshapes: trackingConfig.doAcquireFaceMetrics,
      baseOptions: {
        delegate: trackingConfig.cpuOrGpuString,
        modelAssetPath:
          "https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task",
      },
    });
  } catch (error) {
    // I keep the error visible in the console in case the CDN or model fails.
    console.error(error);
  }
}

function setup() {
  createCanvas(windowWidth, windowHeight); // Full-screen canvas for the performance view.
  pixelDensity(1); // Fixed density keeps the particles lighter to render.
  colorMode(HSB, 360, 100, 100, 1); // HSB makes the emotion colour mapping easier to control.
  textFont(HUD_FONT_FALLBACK); // Start with a fallback font until the web font is ready.

  setupCapture(); // Start the webcam capture.
  setupHudFont(); // Ask the browser to load the HUD font.
  seedParticles(STAGE_CONFIG.particleCount); // Build the initial particle pool once.
  predictWebcam(); // Start the MediaPipe prediction loop.
}

// The web font can load after setup, so I mark when it is actually available for the canvas text.
function setupHudFont() {
  if (!document.fonts) {
    // If the browser does not support this API, the fallback font stays active.
    return;
  }

  // This tells the sketch when the custom HUD font is really available.
  document.fonts.load(`16px '${HUD_FONT}'`).then(() => {
    appState.hudFontReady = true;
  });
}

function setupCapture() {
  // The webcam feed is used only for tracking plus the small preview window.
  myCapture = createCapture(
    {
      video: {
        facingMode: "user", // Front camera works better for the project.
      },
      audio: false, // Audio is generated synthetically, so I do not record microphone input here.
    }
  );
  myCapture.size(640, 480); // This is enough detail for stable face tracking.
  myCapture.hide(); // I draw the camera manually later as a small preview.
}


///////// SOUND ENGINE

// Function to start audio by user interaction.
async function startAudioEngine() {
  if (appState.audioReady) {
    return; // If audio already exists, there is no reason to rebuild it.
  }

  try {
    await userStartAudio(); // Browser audio needs a user gesture before it can run.
    initSoundEngine(); // Build all synth layers only once.
    appState.audioReady = true; // Mark the audio engine as active.
    appState.soundPaused = false; // Audio starts in the running state.
  } catch (error) {
    console.error(error);
  }
}

// After audio has started, mouse click toggles the Web Audio context without interrupting the visuals.
async function toggleAudioPlayback() {
  if (!appState.audioReady) {
    await startAudioEngine(); // First click creates the audio engine.
    return;
  }

  const audioContext = getAudioContext(); // p5.sound runs on top of the shared Web Audio context.

  try {
    if (audioContext.state === "running") {
      await audioContext.suspend(); // Suspend stops the sound without destroying the synthesis graph.
      appState.soundPaused = true; // This flag is used by the HUD readout.
    } else {
      await audioContext.resume(); // Resume brings the sound back with the current state preserved.
      appState.soundPaused = false;
    }
  } catch (error) {
    console.error(error);
  }
}

// The sound engine is fully synthesized so the project stays self-contained and can still produce layered timbres.
function initSoundEngine() {
  if (synthVoice) {
    return; // Avoid building duplicate synth objects.
  }

  synthVoice = new p5.Oscillator("triangle"); // Main melodic voice.
  subVoice = new p5.Oscillator("sine"); // Low voice to give the sound more weight.
  padVoice = new p5.Oscillator("triangle"); // Secondary soft voice.
  airNoise = new p5.Noise("pink"); // Breath-like texture layer.
  filterNode = new p5.Filter(); // Shared filter for the main voice and sub voice.
  padFilter = new p5.Filter(); // Separate filter for the pad voice.
  noiseFilter = new p5.Filter(); // Filter for the air noise.
  masterGain = new p5.Gain(); // Final gain node before the speakers.
  amplitudeAnalyzer = new p5.Amplitude(); // Analysis node used by the particles.
  emotionPulse = new p5.Oscillator("triangle"); // Short tone for emotion triggers.
  emotionPulseFilter = new p5.Filter(); // Filter for the trigger tone.
  accentNoise = new p5.Noise("white"); // Noise accent paired with the trigger tone.
  accentNoiseFilter = new p5.Filter(); // Filter for the accent noise.
  delayNode = new p5.Delay(); // Time-based echo.
  reverbNode = new p5.Reverb(); // Reverb for space.

  filterNode.setType("lowpass"); // This keeps the main layer warm.
  padFilter.setType("bandpass"); // This keeps the pad in the middle range.
  noiseFilter.setType("bandpass"); // This shapes the noisy layer into a useful texture.
  emotionPulseFilter.setType("bandpass"); // This makes the trigger tone more focused.
  accentNoiseFilter.setType("highpass"); // This keeps the trigger noise lighter and sharper.

  synthVoice.disconnect(); // Disconnect from the default output first.
  synthVoice.connect(filterNode); // Route the main voice through the main filter.
  subVoice.disconnect();
  subVoice.connect(filterNode); // Route the sub voice through the same filter.
  padVoice.disconnect();
  padVoice.connect(padFilter); // Give the pad its own filter.
  airNoise.disconnect();
  airNoise.connect(noiseFilter); // Route the noise layer to its own filter.

  filterNode.disconnect();
  filterNode.connect(masterGain); // Send the main filtered sound to the master bus.
  padFilter.disconnect();
  padFilter.connect(masterGain); // Send the pad to the same bus.
  noiseFilter.disconnect();
  noiseFilter.connect(masterGain); // Send the noise layer to the same bus.

  emotionPulse.disconnect();
  emotionPulse.connect(emotionPulseFilter); // Trigger tone also joins the master bus.
  emotionPulseFilter.disconnect();
  emotionPulseFilter.connect(masterGain);
  accentNoise.disconnect();
  accentNoise.connect(accentNoiseFilter); // Trigger noise also joins the master bus.
  accentNoiseFilter.disconnect();
  accentNoiseFilter.connect(masterGain);
  masterGain.connect(); // Final bus goes to the speakers.

  synthVoice.start(); // Start every source at zero amplitude.
  synthVoice.amp(0, 0);
  subVoice.start();
  subVoice.amp(0, 0);
  padVoice.start();
  padVoice.amp(0, 0);
  airNoise.start();
  airNoise.amp(0, 0);
  emotionPulse.start();
  emotionPulse.amp(0, 0);
  accentNoise.start();
  accentNoise.amp(0, 0);

  filterNode.freq(600); // Starting cutoff for the main body sound.
  filterNode.res(2.5); // Mild resonance so the filter has shape without whistling.
  padFilter.freq(1200); // Starting centre area for the pad layer.
  padFilter.res(4); // Slightly stronger resonance for the narrower bandpass pad.
  noiseFilter.freq(1600); // Starting brightness for the noise texture.
  noiseFilter.res(4); // Resonance to give the noise a more shaped band.
  emotionPulseFilter.freq(900); // Starting centre frequency for the accent tone.
  emotionPulseFilter.res(8); // Higher resonance to make the accent more pointed.
  accentNoiseFilter.freq(1800); // Starting brightness for the accent noise.
  accentNoiseFilter.res(3); // Moderate resonance for the accent noise.

  // Both effects sit on the final bus so the whole sound can feel a bit wider.
  delayNode.process(masterGain, 0.24, 0.18, 2200); // Short delay time, light feedback, darkened repeats.
  delayNode.drywet(0.14); // Mostly dry so the texture does not get muddy.
  reverbNode.process(masterGain, 4.2, 1.9, false); // Long enough to feel spacious without washing everything out.
  reverbNode.drywet(0.18); // A restrained mix so the reverb supports the sound instead of covering it.

  masterGain.amp(0.62); // Global output level.
  amplitudeAnalyzer.smooth(0.82); // Smoothing makes the visual response steadier.
  amplitudeAnalyzer.setInput(masterGain); // Analyze the final mixed sound, not one single source.
}


////////// MAIN DRAW LOOP

function draw() {
  background(0); // Black background keeps the particles and HUD more visible.

  const activeFace = getPrimaryFace(); // Get the first tracked face from MediaPipe.
  const activeBlendshapeMap = getPrimaryBlendshapeMap(); // Convert the blendshape list into a simple object.
  appState.hasFace = Boolean(activeFace); // Store whether a face is currently visible.
  appState.faceProximity = getFaceProximity(activeFace); // Estimate distance from the camera.

  if (activeFace) {
    // If there is a face, I update both the geometric controls and the emotion layer.
    featureState.raw = extractFaceFeatures(activeFace);
    smoothFeatures(featureState.raw);
    updateEmotionState(activeBlendshapeMap);
  } else {
    // If the face disappears, I fade the controls down instead of snapping to zero.
    decayFeatures();
    updateEmotionState(null);
  }

  updateSound(); // Turn the current face state into sound changes.
  updateParticles(activeFace); // Move the particle system using the same face state.
  drawParticles(); // Draw the particle field first.
  drawVideoPreview(); // Draw the small webcam reference window.
  drawHUD(); // Draw the interface on top of everything else.
}


/////// TRACKING FACE FEATURES

// Tracking runs in its own loop so the webcam analysis is not locked to the visual frame rate.
async function predictWebcam() {
  if (
    myCapture &&
    myCapture.elt &&
    myCapture.elt.readyState >= 2 &&
    lastVideoTime !== myCapture.elt.currentTime &&
    myFaceLandmarker
  ) {
    // MediaPipe reads the current webcam frame and returns landmarks plus blendshapes.
    faceLandmarks = myFaceLandmarker.detectForVideo(
      myCapture.elt,
      performance.now()
    );
    lastVideoTime = myCapture.elt.currentTime; // Store the time so the same frame is not processed twice.
  }

  window.requestAnimationFrame(predictWebcam); // Keep the tracking loop alive.
}

function getPrimaryFace() {
  if (!faceLandmarks || !faceLandmarks.faceLandmarks) {
    return null; // If MediaPipe has no face result yet, return nothing.
  }

  return faceLandmarks.faceLandmarks[0] || null; // This project only uses one face at a time.
}

// These measurements turn landmark positions into normalized controls that still work if the face moves in space.
function extractFaceFeatures(face) {
  const eyeDistance =
    landmarkDistance(face[FACE_POINTS.leftEyeOuter], face[FACE_POINTS.rightEyeOuter]) || 1; // Eye distance is my main normalization reference.

  const mouthOpenRaw =
    landmarkDistance(face[FACE_POINTS.mouthUpper], face[FACE_POINTS.mouthLower]) /
    eyeDistance; // Mouth opening normalized by face size.
  const mouthWidthRaw =
    landmarkDistance(face[FACE_POINTS.mouthLeft], face[FACE_POINTS.mouthRight]) /
    eyeDistance; // Mouth width normalized by face size.
  const leftEyeRaw =
    landmarkDistance(face[FACE_POINTS.leftEyeUpper], face[FACE_POINTS.leftEyeLower]) /
    eyeDistance; // Left eye openness normalized by face size.
  const rightEyeRaw =
    landmarkDistance(face[FACE_POINTS.rightEyeUpper], face[FACE_POINTS.rightEyeLower]) /
    eyeDistance; // Right eye openness normalized by face size.
  const browLeftRaw =
    abs(face[FACE_POINTS.leftEyeUpper].y - face[FACE_POINTS.browLeft].y) / eyeDistance; // Left brow height relative to the eye.
  const browRightRaw =
    abs(face[FACE_POINTS.rightEyeUpper].y - face[FACE_POINTS.browRight].y) / eyeDistance; // Right brow height relative to the eye.
  const headTiltRaw =
    atan2(
      face[FACE_POINTS.rightEyeOuter].y - face[FACE_POINTS.leftEyeOuter].y,
      face[FACE_POINTS.rightEyeOuter].x - face[FACE_POINTS.leftEyeOuter].x
    ) / 0.45; // Eye line angle converted into a smaller control range.

  return {
    mouthOpen: constrain(map(mouthOpenRaw, 0.015, 0.11, 0, 1), 0, 1), // Normalized mouth opening for sound and emotion.
    mouthWidth: constrain(map(mouthWidthRaw, 0.22, 0.5, 0, 1), 0, 1), // Normalized mouth width.
    browRaise: constrain(map((browLeftRaw + browRightRaw) * 0.5, 0.03, 0.085, 0, 1), 0, 1), // Average brow lift from both sides.
    eyeOpen: constrain(map((leftEyeRaw + rightEyeRaw) * 0.5, 0.012, 0.05, 0, 1), 0, 1), // Average openness from both eyes.
    headTilt: constrain(headTiltRaw, -1, 1), // Final head tilt in a compact -1 to 1 range.
  };
}

// A small amount of smoothing makes the instrument more playable.
function smoothFeatures(nextFeatures) {
  for (const key of FEATURE_KEYS) {
    featureState.smooth[key] = lerp(featureState.smooth[key], nextFeatures[key], 0.16); // Ease each feature toward the latest value.
  }

  featureState.smooth.headTilt = lerp(
    featureState.smooth.headTilt,
    nextFeatures.headTilt,
    0.12 // Tilt is eased separately because it can feel more sensitive.
  );
}

function decayFeatures() {
  // When the face is lost, I keep decaying the last state instead of clearing everything instantly.
  for (const key of FEATURE_KEYS) {
    featureState.smooth[key] = lerp(featureState.smooth[key], 0, 0.08);
  }

  featureState.smooth.headTilt = lerp(featureState.smooth.headTilt, 0, 0.08);
}


///////// EMOTION ACCENTS AND CONTINUOUS SOUND MAPPING

// This avoids the accent sound retriggering every single frame during a held expression.
function maybeTriggerEmotionAudio() {
  if (!appState.audioReady || emotionState.current === "idle") {
    // I avoid trigger accents when audio is off or when no clear emotion is active.
    return;
  }

  const style = EMOTION_STYLES[emotionState.current]; // Current emotion style gives the cooldown and accent character.
  const now = millis(); // Current running time in milliseconds.
  const confidence = constrain(emotionState.confidence, 0, 1); // Keep confidence inside a safe 0 to 1 range.
  const shouldRetrigger =
    now - emotionState.lastTriggerTime > style.triggerCooldown && confidence > 0.34; // Wait for both enough time and enough confidence.

  if (shouldRetrigger) {
    // I call the short accent directly here because there is only one accent path now.
    triggerFallbackEmotionPulse(style, emotionState.current, confidence);
    emotionState.lastTriggerTime = now;
  }
}

// These short accents give each emotion a small sonic event on top of the continuous drone.
function triggerFallbackEmotionPulse(style, emotion, intensity) {
  if (!emotionPulse || !accentNoise) {
    return;
  }

  const attack = 0.01; // Fast attack makes the accent feel like an event instead of a fade-in.
  let pulseFrequency = style.pulseFreq * random(0.94, 1.08) * (1 + intensity * 0.22); // Base accent pitch with slight randomness and intensity scaling.
  let pulseAmplitude = 0.04 + intensity * 0.12; // Tone loudness grows with emotion strength.
  let noiseAmplitude = 0.006 + intensity * 0.016; // Noise layer also grows with emotion strength.
  let pulseRelease = style.release; // Release time comes from the active emotion style.
  let pulsePan = random(-0.55, 0.55); // Small random pan helps accents feel less static.
  let noiseType = "white"; // Default noise colour before emotion-specific changes.
  let filterType = "bandpass"; // Default accent filter shape.
  let filterFrequency = 900; // Default centre frequency for the accent filter.
  let filterResonance = 8; // Default resonance so the accent stays focused.
  let noiseCutoff = 1800; // Default brightness for the accent noise.

  if (emotion === "angry") {
    pulseFrequency *= 0.82;
    pulseAmplitude += 0.04;
    noiseAmplitude += 0.01;
    pulseRelease *= 0.8;
    noiseCutoff = 1400;
    filterFrequency = 320;
    filterResonance = 12;
  } else if (emotion === "happy") {
    pulseFrequency *= 1.22;
    pulseAmplitude += 0.02;
    pulseRelease *= 0.9;
    noiseType = "pink";
    noiseCutoff = 2600;
    filterFrequency = 1400;
    filterResonance = 7;
  } else if (emotion === "disgust") {
    pulseFrequency *= 0.9;
    pulseAmplitude *= 0.82;
    pulseRelease *= 1.3;
    noiseType = "brown";
    filterType = "notch";
    filterFrequency = 480;
    filterResonance = 10;
    noiseCutoff = 900;
  } else if (emotion === "surprised") {
    pulseFrequency *= 1.45;
    pulseAmplitude += 0.03;
    noiseAmplitude += 0.018;
    pulseRelease *= 0.72;
    noiseCutoff = 3200;
    filterFrequency = 2200;
    filterResonance = 9;
  } else if (emotion === "fear") {
    pulseFrequency *= 1.05 + random(-0.08, 0.08);
    pulseAmplitude *= 0.92;
    noiseAmplitude += 0.014;
    noiseType = "white";
    noiseCutoff = 2400;
    filterFrequency = 1200;
    filterResonance = 13;
  } else if (emotion === "sadness") {
    pulseFrequency *= 0.72;
    pulseAmplitude *= 0.76;
    pulseRelease *= 1.8;
    noiseAmplitude *= 0.45;
    noiseType = "brown";
    noiseCutoff = 700;
    filterFrequency = 260;
    filterResonance = 6;
  }

  emotionPulse.setType(style.pulseWave); // Choose the accent oscillator shape for this emotion.
  emotionPulseFilter.setType(filterType); // Choose the filter mode for this emotion.
  emotionPulseFilter.freq(filterFrequency, 0.01); // Smoothly move the filter to the chosen centre frequency.
  emotionPulseFilter.res(filterResonance, 0.01); // Smoothly move the resonance to the chosen amount.
  accentNoise.setType(noiseType); // Choose the accent noise colour.
  accentNoiseFilter.freq(noiseCutoff, 0.01); // Smoothly move the noise brightness.

  emotionPulse.freq(pulseFrequency, 0.01);
  emotionPulse.pan(pulsePan, 0.02);
  emotionPulse.amp(pulseAmplitude, attack);
  emotionPulse.amp(0, pulseRelease);

  accentNoise.amp(noiseAmplitude, attack);
  accentNoise.amp(0, pulseRelease * 0.9);
}

// The main instrument is continuous, but I still quantize pitch so the result feels intentional rather than arbitrary.
function updateSound() {
  if (!appState.audioReady || !synthVoice || !subVoice || !padVoice || !airNoise) {
    // The HUD stays at zero until the sound engine is actually running.
    engineState.mainFreq = 0;
    engineState.cutoff = 0;
    engineState.level = 0;
    return;
  }

  const emotion = emotionState.current; // Current stable emotion label.
  const confidence = constrain(emotionState.confidence, 0, 1); // Current stable emotion strength.
  const root = EMOTION_ROOTS[emotion] || EMOTION_ROOTS.idle; // Root note chosen for the active emotion.
  const scale = EMOTION_SCALES[emotion] || EMOTION_SCALES.idle; // Pitch collection chosen for the active emotion.

  // Brow and mouth movement push the note up through the chosen scale.
  const rawMidi =
    root +
    featureState.smooth.browRaise * 14 +
    featureState.smooth.mouthOpen * 8 +
    featureState.smooth.eyeOpen * 3;

  const mainMidi = snapNoteToScale(rawMidi, root, scale); // Pull the raw note onto the nearest note of the chosen scale.
  let mainFreq = midiToFreq(mainMidi); // Convert the snapped MIDI note into hertz.
  let bassFreq = max(45, mainFreq * 0.5); // Bass follows one octave below, with a floor to avoid going too low.
  let padFreq = midiToFreq(mainMidi + 7); // Pad stays a fifth above the main note.

  // Amplitude starts from a small base and then opens with expression.
  let mainAmp = appState.hasFace ? 0.024 : 0;
  mainAmp += featureState.smooth.mouthOpen * 0.08;
  mainAmp += featureState.smooth.browRaise * 0.04;

  let bassAmp = 0.018 + featureState.smooth.mouthOpen * 0.03;
  let padAmp = 0.012 + featureState.smooth.mouthWidth * 0.03;
  let noiseAmp = 0.003 + featureState.smooth.eyeOpen * 0.012 + confidence * 0.008;

  let cutoff = map(featureState.smooth.mouthOpen, 0, 1, 320, 3000); // Mouth opening brightens the main sound.
  let padCutoff = map(featureState.smooth.mouthWidth, 0, 1, 900, 2400); // Mouth width opens the pad timbre.
  let noiseCutoff = map(featureState.smooth.eyeOpen, 0, 1, 900, 3600); // Eye openness brightens the noise texture.
  let resonance = map(featureState.smooth.mouthWidth, 0, 1, 2, 10); // Mouth width also sharpens the filter emphasis.
  let pan = featureState.smooth.headTilt * 0.9; // Head tilt moves the sound left and right.

  // Wave type and modulation change with the current emotion.
  let mainWave = "triangle";
  let padWave = "triangle";
  let wobbleAmount = 0.5;
  let wobbleSpeed = 0.015;
  let delayMix = 0.14;
  let reverbMix = 0.18;
  const proximityGain = lerp(0.7, 1.45, appState.faceProximity); // Closer face means stronger overall loudness.

  if (emotion === "angry") {
    mainWave = "sawtooth";
    padWave = "square";
    cutoff *= 0.75;
    resonance += 3 * confidence;
    mainAmp += 0.05 * confidence;
    bassAmp += 0.03 * confidence;
    padAmp += 0.01 * confidence;
    noiseAmp += 0.012 * confidence;
    noiseCutoff *= 0.7;
    delayMix = 0.08;
    reverbMix = 0.1;
    wobbleAmount = 1.8;
    wobbleSpeed = 0.03;
  } else if (emotion === "happy") {
    mainWave = "triangle";
    padWave = "sine";
    mainFreq *= 1.03;
    padFreq *= 1.08;
    cutoff *= 1.14;
    mainAmp += 0.04 * confidence;
    padAmp += 0.03 * confidence;
    noiseAmp += 0.014 * confidence;
    noiseCutoff *= 1.18;
    delayMix = 0.18;
    reverbMix = 0.16;
    wobbleAmount = 1.1;
    wobbleSpeed = 0.025;
  } else if (emotion === "disgust") {
    mainWave = "square";
    padWave = "triangle";
    mainFreq *= 0.92;
    padFreq *= 0.88;
    cutoff *= 0.62;
    padCutoff *= 0.7;
    noiseCutoff *= 0.58;
    padAmp *= 0.75;
    noiseAmp *= 0.65;
    delayMix = 0.1;
    reverbMix = 0.14;
    wobbleAmount = 0.3;
    wobbleSpeed = 0.01;
  } else if (emotion === "surprised") {
    mainWave = "triangle";
    padWave = "sawtooth";
    mainFreq *= 1.08;
    padFreq *= 1.15;
    cutoff *= 1.24;
    padAmp += 0.028 * confidence;
    noiseAmp += 0.018 * confidence;
    noiseCutoff *= 1.3;
    delayMix = 0.2;
    reverbMix = 0.22;
    wobbleAmount = 1.2;
    wobbleSpeed = 0.03;
  } else if (emotion === "fear") {
    mainWave = "square";
    padWave = "triangle";
    resonance += 2.4;
    padAmp += 0.016 * confidence;
    noiseAmp += 0.016 * confidence;
    delayMix = 0.16;
    reverbMix = 0.24;
    wobbleAmount = 3.2;
    wobbleSpeed = 0.07;
  } else if (emotion === "sadness") {
    mainWave = "triangle";
    padWave = "sine";
    mainFreq *= 0.88;
    padFreq *= 0.83;
    cutoff *= 0.58;
    padCutoff *= 0.72;
    noiseCutoff *= 0.55;
    mainAmp *= 0.82;
    bassAmp += 0.02;
    padAmp *= 0.82;
    noiseAmp *= 0.5;
    delayMix = 0.22;
    reverbMix = 0.32;
    wobbleAmount = 0.45;
    wobbleSpeed = 0.012;
  }

  // This small wobble stops the tone from feeling too static.
  const wobble = sin(frameCount * wobbleSpeed) * wobbleAmount;

  // Face distance also affects perceived intensity: close face = bigger and louder instrument.
  mainAmp *= proximityGain;
  bassAmp *= proximityGain;
  padAmp *= proximityGain;
  noiseAmp *= lerp(0.85, 1.35, appState.faceProximity);

  synthVoice.setType(mainWave);
  padVoice.setType(padWave);

  synthVoice.freq(mainFreq + wobble, 0.08);
  synthVoice.amp(mainAmp, 0.1);
  subVoice.freq(bassFreq, 0.1);
  subVoice.amp(bassAmp, 0.12);
  padVoice.freq(padFreq - wobble * 0.5, 0.12);
  padVoice.amp(padAmp, 0.16);
  airNoise.amp(noiseAmp, 0.16);

  synthVoice.pan(pan, 0.1);
  subVoice.pan(pan * 0.45, 0.1);
  padVoice.pan(-pan * 0.35, 0.12);

  filterNode.freq(cutoff, 0.08);
  filterNode.res(resonance, 0.08);
  padFilter.freq(padCutoff, 0.12);
  padFilter.res(3 + confidence * 4, 0.12);
  noiseFilter.freq(noiseCutoff, 0.12);
  noiseFilter.res(3 + confidence * 6, 0.12);

  delayNode.drywet(delayMix);
  reverbNode.drywet(reverbMix);

  // These values feed the live HUD readout.
  engineState.mainFreq = mainFreq;
  engineState.cutoff = cutoff;
  engineState.level = mainAmp;
}


///////// HUD design

function drawHUD() {
  // The font is checked every frame because the web font can finish loading after setup.
  textFont(appState.hudFontReady ? HUD_FONT : HUD_FONT_FALLBACK);
  updateHudBars();
  drawTopHUD();
  drawBottomEmotionHUD();
}

function updateHudBars() {
  for (const emotion of EMOTION_KEYS) {
    // The bars move with a small delay.
    hudState.bars[emotion] = lerp(hudState.bars[emotion], emotionState.scores[emotion], 0.18);
  }
}

function drawTopHUD() {
  const y = HUD_CONFIG.margin;
  const leftWidth = 180;
  const rightWidth = 205;
  const gap = HUD_CONFIG.panelGap;
  const dateText = getHudDateString();

  // Left side: author credit and date.
  drawHudLabelValue(HUD_CONFIG.margin + 16, y + 14, "by", "Andrés Serna", LEFT);
  drawHudLabelValue(HUD_CONFIG.margin + leftWidth + gap + 16, y + 14, "date", dateText, LEFT);

  // Centre: title of the project.
  textAlign(CENTER, CENTER);
  noStroke();
  fill(0, 0, 92, 0.92);
  textSize(20);
  textStyle(NORMAL);
  // I add spacing between letters so the title sits more like a screen interface than body text.
  text(spacedTitle(PROJECT_TITLE), width * 0.5, y + HUD_CONFIG.topHeight * 0.5 + 1);

  // Right side: interaction hint plus live sound numbers.
  drawHudLabelValue(
    width - rightWidth * 2 - gap - HUD_CONFIG.margin + 6,
    y + 14,
    "interaction",
    "click to start / pause",
    LEFT
  );
  drawHudLabelValue(
    width - rightWidth - HUD_CONFIG.margin + 6,
    y + 14,
    "instrument",
    getEngineReadoutText(),
    LEFT
  );
}

function drawBottomEmotionHUD() {
  const outerX = HUD_CONFIG.margin;
  const outerY = height - HUD_CONFIG.bottomHeight - HUD_CONFIG.margin;
  const outerW = width - HUD_CONFIG.margin * 2;
  const innerPadding = 18;
  const gap = 16;
  const itemW = (outerW - innerPadding * 2 - gap * (HUD_EMOTIONS.length - 1)) / HUD_EMOTIONS.length;

  // Each emotion gets the same amount of space so the display reads like a monitor strip.
  for (let i = 0; i < HUD_EMOTIONS.length; i++) {
    const item = HUD_EMOTIONS[i];
    const x = outerX + innerPadding + i * (itemW + gap);
    const y = outerY + 18;
    drawEmotionMeter(x, y, itemW, item);
  }
}

function drawEmotionMeter(x, y, w, item) {
  const score = constrain(hudState.bars[item.key], 0, 1);
  const style = EMOTION_STYLES[item.key];
  const percentText = nf(score * 100, 2, 0) + "%";
  const barY = y + 28;
  const fillW = score > 0.001 ? max(4, score * w) : 0;

  // The label and percentage stay on the same line like a compact monitor strip.
  noStroke();
  fill(0, 0, 72, 0.95);
  textAlign(LEFT, BASELINE);
  textSize(13);
  text(item.label, x, y);

  fill(0, 0, 45, 0.95);
  textAlign(RIGHT, BASELINE);
  text(percentText, x + w, y);

  noStroke();
  fill(0, 0, 16, 0.78);
  rect(x, barY, w, HUD_CONFIG.barHeight, 8);

  if (fillW > 0) {
    // I draw a soft layer first, then a brighter core on top.
    fill(style.hueMin, style.sat, style.bri, 0.24);
    rect(x, barY, fillW, HUD_CONFIG.barHeight, 8);

    fill(style.hueMin, style.sat, style.bri, 0.92);
    rect(x, barY + 1, max(2, fillW - 2), HUD_CONFIG.barHeight - 2, 8);
  }
}

function drawHudLabelValue(x, y, label, value, alignMode) {
  // This helper keeps the small top labels visually consistent.
  textAlign(alignMode, TOP);
  noStroke();
  fill(0, 0, 46, 0.9);
  textSize(10);
  text(label.toUpperCase(), x, y);

  fill(0, 0, 92, 0.96);
  textSize(14);
  text(value, x, y + 12);
}

// The webcam stays visible only as a small reference window for the performer.
function drawVideoPreview() {
  if (!myCapture) {
    return;
  }

  const previewWidth = min(STAGE_CONFIG.previewWidth, width * 0.28);
  const previewHeight = previewWidth * STAGE_CONFIG.previewAspect;
  const previewX = width - previewWidth - STAGE_CONFIG.previewMargin;
  const targetPreviewY =
    height - previewHeight - STAGE_CONFIG.previewMargin - HUD_CONFIG.bottomHeight - HUD_CONFIG.margin;
  const previewY = max(HUD_CONFIG.margin + HUD_CONFIG.topHeight + 18, targetPreviewY);
  const style = EMOTION_STYLES[emotionState.current];

  noStroke();
  fill(0, 0, 6, 0.82);
  rect(previewX - 8, previewY - 8, previewWidth + 16, previewHeight + 16, 18);

  push();
  translate(previewX + previewWidth, previewY);
  scale(-1, 1);
  tint(255, 210);
  image(myCapture, 0, 0, previewWidth, previewHeight);
  pop();

  noFill();
  stroke(style.hueMin, style.sat, style.bri, 0.8);
  strokeWeight(2);
  rect(previewX, previewY, previewWidth, previewHeight, 14);
}

///////// HELPERS

function toCanvasPoint(landmark) {
  return {
    x: map(landmark.x, 0, 1, width, 0), // Mirror the x axis so the interaction behaves like a mirror.
    y: map(landmark.y, 0, 1, 0, height), // Keep the y axis in the usual screen direction.
  };
}

function landmarkDistance(a, b) {
  return dist(a.x, a.y, b.x, b.y); // Reusable 2D distance helper for normalized landmarks.
}

function getFaceProximity(face) {
  if (!face) {
    // I keep a middle value when the face disappears so the system does not collapse suddenly.
    return 0.35;
  }

  const faceSize = landmarkDistance(
    face[FACE_POINTS.leftEyeOuter],
    face[FACE_POINTS.rightEyeOuter]
  );

  // Eye distance is the simplest stable cue here for estimating camera proximity.
  return constrain(map(faceSize, 0.07, 0.2, 0, 1), 0, 1);
}

function getHudDateString() {
  // The date is generated live so it always matches the current day.
  return new Date().toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function getEngineReadoutText() {
  if (!appState.audioReady) {
    // Before audio starts, I show zero values.
    return "0hz / 0hz / 0%";
  }

  if (appState.soundPaused) {
    // When the context is suspended, I make that explicit in the interface.
    return "paused / 0hz / 0%";
  }

  const freqText = int(engineState.mainFreq) + "hz";
  const cutoffText =
    engineState.cutoff >= 1000
      ? nf(engineState.cutoff / 1000, 1, 2) + "k"
      : int(engineState.cutoff) + "hz";
  const levelText = nf(engineState.level * 100, 2, 0) + "%";

  return freqText + " / " + cutoffText + " / " + levelText;
}

function spacedTitle(textValue) {
  return textValue.split("").join(" "); // Extra spacing makes the title feel more futuristic.
}

// This picks the nearest note from the scale for the current emotion.
function snapNoteToScale(rawMidi, rootMidi, scale) {
  let bestMidi = rootMidi;
  let bestDistance = Infinity;
  const centreOctave = floor((rawMidi - rootMidi) / 12);

  for (let octaveOffset = centreOctave - 1; octaveOffset <= centreOctave + 1; octaveOffset += 1) {
    for (const degree of scale) {
      const candidateMidi = rootMidi + octaveOffset * 12 + degree;
      const distance = abs(candidateMidi - rawMidi);

      if (distance < bestDistance) {
        bestDistance = distance;
        bestMidi = candidateMidi;
      }
    }
  }

  return bestMidi;
}

function mousePressed() {
  toggleAudioPlayback();
}

function touchStarted() {
  toggleAudioPlayback();
  return false;
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}
